<?xml version="1.0" encoding="utf-8"?>
<Database Name="GraphVizDebugging" EntityNamespace="TreeVisualiser" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JON-LAPTOP\SQL2008;Initial Catalog=GraphVizDebugging;Integrated Security=True" SettingsObjectName="TreeVisualiser.Properties.Settings" SettingsPropertyName="GraphVizDebuggingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.fieldspec" Member="FieldSpecs">
    <Type Name="FieldSpec">
      <Column Name="id" Member="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Member="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="field_type" Member="FieldType" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="is_required" Member="IsRequired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.predicate" Member="Predicates">
    <Type Name="Predicate" Modifier="Abstract">
      <Column Name="id" Member="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pred_type" Member="PredicateType" Type="System.String" DbType="NVarChar(20)" IsReadOnly="true" CanBeNull="true" IsDiscriminator="true" />
      <Column Name="is_deleted" Member="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="false" />
      <Type Name="CompoundPredicate" Modifier="Abstract">
        <Column Name="left_child_id" Member="LeftChildId" AccessModifier="Protected" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
        <Column Name="right_child_id" Member="RightChildId" AccessModifier="Protected" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
        <Association Name="Predicate_CompoundPredicate" Member="LeftChild" ThisKey="LeftChildId" OtherKey="Id" Type="Predicate" IsForeignKey="true" />
        <Association Name="Predicate_CompoundPredicate1" Member="RightChild" ThisKey="RightChildId" OtherKey="Id" Type="Predicate" IsForeignKey="true" />
        <Type Name="OrPredicate" InheritanceCode="Or" IsInheritanceDefault="true" />
        <Type Name="AndPredicate" InheritanceCode="And" />
      </Type>
      <Type Name="ComparePredicate" InheritanceCode="Compare">
        <Column Name="field_spec_id" Member="FieldSpecId" AccessModifier="Protected" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
        <Column Name="compare_type" Member="CompareType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
        <Column Name="match_value" Member="MatchValue" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
        <Association Name="FieldSpec_ComparePredicate" Member="FieldSpec" ThisKey="FieldSpecId" OtherKey="Id" Type="FieldSpec" IsForeignKey="true" />
      </Type>
      <Type Name="RootPredicate" InheritanceCode="Root">
        <Column Name="root_child_id" Member="RootChildId" AccessModifier="Protected" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
        <Association Name="Predicate_RootPredicate" Member="RootChild" ThisKey="RootChildId" OtherKey="Id" Type="Predicate" IsForeignKey="true" />
      </Type>
    </Type>
  </Table>
</Database>